name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - version.txt
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version
        id: version
        run: echo "version=$(head -c -1 version.txt)" >> $GITHUB_ENV
          
      - name: Install Binaryen
        run: |
          BINARYEN_VERSION="version_116"
          wget https://github.com/WebAssembly/binaryen/releases/download/$BINARYEN_VERSION/binaryen-$BINARYEN_VERSION-x86_64-linux.tar.gz
          tar -xzf binaryen-$BINARYEN_VERSION-x86_64-linux.tar.gz
          sudo cp binaryen-$BINARYEN_VERSION/bin/* /usr/local/bin/

      - name: Generate dist folder
        working-directory: wasm
        run: make build

      - name: Push to deploy branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./wasm/dist
          publish_branch: deploy
          destination_dir: dist

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          tag_name: ${{ env.version }}
          name: Release ${{ env.version }}
